#!/usr/bin/env python3
"""Run small two-site DMRG cases and write ``docs/DMRG_REPORT.md``.

Small systems (N<=6) are compared against exact diagonalization; an N=8 smoke
checks finiteness, energy decrease, and bond-dim caps (no dense ED).

Reported content (per docs/DMRG_PROTOCOL.md stop conditions):
- exact comparison (N<=6),
- DMRG energy history,
- chi, truncation errors, bond dims,
- H_eff hermiticity,
- pass/fail, known limitations.
"""

from __future__ import annotations

import argparse
import os
import sys
import time
from pathlib import Path

import torch as tc

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from latticetn.mps import MPS  # noqa: E402
from latticetn.mpo import MPO  # noqa: E402
from latticetn import dmrg as D  # noqa: E402
from latticetn import contractions as K  # noqa: E402
from latticetn.operators import heisenberg_dense, exact_ground_energy  # noqa: E402

DTYPE = tc.complex128


def _exact(N: int):
    H = heisenberg_dense(N, dtype=DTYPE, device="cpu")
    return exact_ground_energy(H)


def _hermiticity(mps, mpo, i=1) -> float:
    t = D.mixed_canonical_two_site(mps, i)
    tmp = MPS.from_tensors(t, dtype=DTYPE, device="cpu")
    H = D.effective_hamiltonian(tmp, mpo, i)
    return float((H - H.conj().t()).abs().max())


def _dmrg_case(N, chi, sweeps, seed=0):
    tc.manual_seed(seed)
    mps = MPS(N, 2, chi, dtype=DTYPE)
    mpo = MPO.from_bonds(N, 2, dtype=DTYPE, device="cpu").generate_heisenberg(J=1.0)
    t0 = time.perf_counter()
    res = D.run_dmrg(mps, mpo, chi=chi, num_sweeps=sweeps, seed=seed)
    res["runtime_s"] = time.perf_counter() - t0
    res["heff_herm_err"] = _hermiticity(mps, mpo, i=min(1, N - 2))
    return res


def run_smoke() -> dict:
    os.environ.setdefault("CUDA_VISIBLE_DEVICES", "")
    report: dict = {
        "convention": "H = J * sum_i S_i.S_{i+1}, S = sigma/2, J = 1.0, open boundary, complex128",
        "dtype": str(DTYPE),
        "cases": [],
        "smoke": {},
        "checks": {},
        "pass": True,
        "known_limitations": [
            "Two-site DMRG is a NON-differentiable classical optimizer; not part of the autograd energy path.",
            "H_eff is built by applying to basis vectors (D small); fine for N<=8/10, not optimized for large N.",
            "Native MPO Rayleigh quotient (rayleigh_energy_native) is used for the global DMRG energy.",
            "No TEBD / TDVP / GPU performance benchmark; no long training.",
        ],
    }

    # exact-comparison cases (N<=6)
    exact_pass = True
    for N, chi in [(4, 8), (6, 8)]:
        res = _dmrg_case(N, chi, sweeps=4, seed=0)
        ok = (abs(res["final_energy"] - res["exact_energy"]) < 1e-6
              and not res["below_ground"]
              and res["heff_herm_err"] < 1e-10)
        res["pass"] = bool(ok)
        exact_pass = exact_pass and ok
        report["cases"].append(res)

    # N=8 smoke (no dense ED)
    tc.manual_seed(0)
    N8, chi8 = 8, 8
    mps8 = MPS(N8, 2, chi8, dtype=DTYPE)
    mpo8 = MPO.from_bonds(N8, 2, dtype=DTYPE, device="cpu").generate_heisenberg(J=1.0)
    e_init8 = float(K.rayleigh_energy_native(mps8, mpo8))
    t0 = time.perf_counter()
    res8 = D.run_dmrg(mps8, mpo8, chi=chi8, num_sweeps=3, seed=0)
    res8["runtime_s"] = time.perf_counter() - t0
    res8["initial_energy"] = e_init8
    res8["heff_herm_err"] = _hermiticity(mps8, mpo8, i=1)
    res8["pass"] = bool(
        tc.isfinite(tc.as_tensor(res8["final_energy"]))
        and res8["final_energy"] < e_init8 + 1e-6
        and res8["final_max_bond"] <= chi8
        and res8["heff_herm_err"] < 1e-10
        and all(0.0 <= e <= 1.0 + 1e-12
                for h in res8["history"] for e in h["truncation_errors"])
        and res8["runtime_s"] < 120.0
    )
    report["smoke"] = res8

    checks = {
        "n4_exact_match": report["cases"][0]["pass"],
        "n6_exact_match": report["cases"][1]["pass"],
        "heff_hermitian_all": all(c["heff_herm_err"] < 1e-10 for c in report["cases"])
                              and res8["heff_herm_err"] < 1e-10,
        "no_below_ground": all(not c["below_ground"] for c in report["cases"]),
        "n8_smoke": res8["pass"],
    }
    report["checks"] = checks
    report["pass"] = all(checks.values())
    return report


def _fmt_history(res) -> str:
    rows = []
    for h in res["history"]:
        rows.append(
            f"| {h['sweep']} | {h['direction']} | {h['energy']:.10f} | "
            f"{h['max_trunc']:.2e} | {h['max_bond']} | {h['bond_dims']} |"
        )
    return "\n".join(rows)


def render_report_md(report: dict) -> str:
    L: list[str] = []
    L.append("# Stage 4A Two-Site DMRG Report")
    L.append("")
    L.append("Generated by `scripts/run_dmrg_small.py`.")
    L.append("")
    L.append("## Convention")
    L.append("")
    L.append(f"`{report['convention']}`")
    L.append(f"- dtype: `{report['dtype']}`")
    L.append("")
    L.append("## Exact comparison (N<=6)")
    L.append("")
    L.append("| N | chi | sweeps | exact E0 | DMRG final E | abs err | below ground | H_eff herm err | max bond | runtime_s | pass |")
    L.append("|---:|---:|---:|---:|---:|---:|:---:|---:|---:|---:|:---|")
    for c in report["cases"]:
        L.append(f"| {c['N']} | {c['chi']} | {c['num_sweeps']} | "
                 f"{c['exact_energy']:.10f} | {c['final_energy']:.10f} | "
                 f"{abs(c['final_energy'] - c['exact_energy']):.2e} | "
                 f"{c['below_ground']} | {c['heff_herm_err']:.2e} | "
                 f"{c['final_max_bond']} | {c['runtime_s']:.2f} | "
                 f"{'PASS' if c['pass'] else 'FAIL'} |")
    L.append("")
    L.append("### DMRG energy history")
    L.append("")
    for c in report["cases"]:
        L.append(f"N={c['N']}, chi={c['chi']}:")
        L.append("")
        L.append("| sweep | direction | energy | max trunc | max bond | bond dims |")
        L.append("|---:|---|---:|---:|---:|---|")
        L.append(_fmt_history(c))
        L.append("")
    L.append("## N=8 smoke (no dense ED)")
    L.append("")
    s = report["smoke"]
    L.append(f"- N: `{s['N']}`, chi: `{s['chi']}`, sweeps: `{s['num_sweeps']}`")
    L.append(f"- initial energy: `{s['initial_energy']:.10f}`")
    L.append(f"- final energy: `{s['final_energy']:.10f}` "
             f"(finite: `{bool(tc.isfinite(tc.as_tensor(s['final_energy'])))}`)")
    L.append(f"- final max bond: `{s['final_max_bond']}` (chi cap `{s['chi']}`)")
    L.append(f"- H_eff herm err (bond 1): `{s['heff_herm_err']:.2e}`")
    L.append(f"- runtime: `{s['runtime_s']:.2f}s`")
    L.append("")
    L.append("| sweep | direction | energy | max trunc | max bond |")
    L.append("|---:|---|---:|---:|---:|")
    for h in s["history"]:
        L.append(f"| {h['sweep']} | {h['direction']} | {h['energy']:.10f} | "
                 f"{h['max_trunc']:.2e} | {h['max_bond']} |")
    L.append("")
    L.append("## Overall pass/fail")
    L.append("")
    L.append(f"**pass: `{report['pass']}`**")
    L.append("")
    L.append("| check | passed |")
    L.append("|---|:---|")
    for k, v in report["checks"].items():
        L.append(f"| {k} | {v} |")
    L.append("")
    L.append("## Known limitations")
    L.append("")
    for lim in report["known_limitations"]:
        L.append(f"- {lim}")
    L.append("")
    return "\n".join(L)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--markdown-output", type=Path,
                        default=ROOT / "docs" / "DMRG_REPORT.md")
    args = parser.parse_args()

    report = run_smoke()
    args.markdown_output.parent.mkdir(parents=True, exist_ok=True)
    args.markdown_output.write_text(render_report_md(report), encoding="utf-8")
    print(f"dmrg smoke: pass={report['pass']} report -> {args.markdown_output}")
    return 0 if report["pass"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
